# Generated by Django 3.1.1 on 2020-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
