# Generated by Django 3.1.1 on 2020-09-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userregister_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='birth',
        ),
        migrations.AddField(
            model_name='userregister',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
